[build]
  # Assuming your React or static frontend is built into a directory named 'dist' or 'build'
  # If your build folder is different, change 'build' below.
  publish = "build"
  command = "npm run build" # Or whatever your build command is

# This section creates the proxy (redirect) rule
[[redirects]]
  # When the frontend tries to access /api/endpoint...
  from = "/api/*"
  # ...redirect it to the backend on Heroku
  to = "https://fastfoodnutritionn.herokuapp.com/api/:splat"
  status = 200
  force = true